### ISSUE TITLE
Improve Contributors.md

### ISSUE THREAD

**Issue by Vrindagupta6828** [edualgo/edualgo-app-demo#19]
Write proper steps to run the app in your local machine.

**Comment by Vrindagupta6828** [comment]
@Abhijit2505 Please look for this issue and if you find it legitimate award me points for nwoc.

**Comment by Abhijit2505** [comment]
@Vrindagupta6828 I believe the steps are written in the README section already. And we don't regard this as an issue.

Hence closing it.
