### ISSUE TITLE
Code of Conduct

### ISSUE THREAD

**Issue by Tejas1510** [edualgo/edualgo-app-demo#20]
The project is currently missing the Code of Conduct file which is important for open source project
So can I go for it @Abhijit2505

**Comment by Abhijit2505** [comment]
@Tejas1510 , I am assuming you have never contributed to our projects or neither being a part of our organization.

So even if I assign you the issue, how are you going to write a code of conduct for something you are quite a newbie.

Kindly explain first.

**Comment by Tejas1510** [comment]
Hello @Abhijit2505 Sir 
Sorry for the delay
I thought since edualgo is becoming a big organization I thought it would be appropriate if it would have a code of conduct which is important for any open source project.
So can I work on it or not
