### ISSUE TITLE
Add Issue template

### ISSUE THREAD

**Issue by KerinPithawala** [edualgo/edualgo-app-demo#21]
Can I make issue templates to enhance the workflow of the repository?

**Comment by Abhijit2505** [comment]
@Kerveyfelix ,  I am assuming you have never contributed to our projects or neither being a part of our organization.

So even if I assign you the issue, how are you going to make an issue template for us?
I think the issue and PR template making is the sole choice of the organization.

So, I would like to request you to pick some other issues.
